version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: Postgres01
    hostname: Host-Postgres01
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

      # Configuración de localización (opcional)
      # LANG: 'es_ES.utf8'
    
    ports:
      - "5432:5432"
    
    volumes:
    # La BD estará almacenada en la misma carpeta del proyecto
      - './postgres:/var/lib/postgresql/data'
    
    # Reiniciar siempre
    restart: always